# Generated by Django 4.2.21 on 2025-06-29 22:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='気持ち名')),
                ('feeling_image', models.ImageField(blank=True, help_text='登録しない場合は、デフォルトの気持ちイメージを使用する', upload_to='image', verbose_name='気持ちイメージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telekoko.feeling', verbose_name='気持ちID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telekoko.group', verbose_name='グループID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telekoko.user', verbose_name='ユーザID')),
            ],
        ),
    ]
